language: Java

jdk:
  - oraclejdk8
branches: 
  only:
    - development
notifications:
  recipients:
  - fecheromero@gmail.com
  - chona.diaz@gmail.com
  - candezunino@gmail.com
  - nadiagutierrez89@yahoo.com.ar
  - iimariano94@gmail.com
  
  email:
    on_success: change
    on_failure: always
